class CountryFlags {
  static const Map<String, String> _flags = {
    'Australien': '🇦🇺',
    'Österreich': '🇦🇹',
    'Belgien': '🇧🇪',
    'Bosnien-Herzegowina': '🇧🇦',
    'Bosnien Herzegowina': '🇧🇦',
    'Bosnien und Herzegowina': '🇧🇦',
    'Bosnia and Herzegovina': '🇧🇦',
    'Brasilien': '🇧🇷',
    'Kanada': '🇨🇦',
    'Kap Verde': '🇨🇻',
    'Kolumbien': '🇨🇴',
    'Tschechien': '🇨🇿',
    'DR Kongo': '🇨🇩',
    'Ecuador': '🇪🇨',
    'Ägypten': '🇪🇬',
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Frankreich': '🇫🇷',
    'Deutschland': '🇩🇪',
    'Ghana': '🇬🇭',
    'Haiti': '🇭🇹',
    'Iran': '🇮🇷',
    'Irak': '🇮🇶',
    'Elfenbeinküste': '🇨🇮',
    'Japan': '🇯🇵',
    'Jordanien': '🇯🇴',
    'Mexiko': '🇲🇽',
    'Marokko': '🇲🇦',
    'Niederlande': '🇳🇱',
    'Neuseeland': '🇳🇿',
    'Norwegen': '🇳🇴',
    'Panama': '🇵🇦',
    'Paraguay': '🇵🇾',
    'Portugal': '🇵🇹',
    'Katar': '🇶🇦',
    'Saudi-Arabien': '🇸🇦',
    'Schottland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Senegal': '🇸🇳',
    'Südafrika': '🇿🇦',
    'Südkorea': '🇰🇷',
    'Spanien': '🇪🇸',
    'Schweden': '🇸🇪',
    'Schweiz': '🇨🇭',
    'Tunesien': '🇹🇳',
    'Türkei': '🇹🇷',
    'USA': '🇺🇸',
    'Uruguay': '🇺🇾',
    'Usbekistan': '🇺🇿',
    'Kroatien': '🇭🇷',
    'Algerien': '🇩🇿',
    'Argentinien': '🇦🇷',
    'Curaçao': '🇨🇼',
  };

  static String getFlag(String country) {
    return _flags[country] ?? '🏳️';
  }
}
