// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp24-S6SkJ9h16IpairkJmx29-7YAijUE',
    appId: '1:506754202518:android:e8cfae9543bcecac143bb7',
    messagingSenderId: '506754202518',
    projectId: 'voleo-sho2303',
    storageBucket: 'voleo-sho2303.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALoMLJbrrp4hlFOfEFOhDSnF41GXigcuo',
    appId: '1:506754202518:ios:f1da49ea9b95ebcb143bb7',
    messagingSenderId: '506754202518',
    projectId: 'voleo-sho2303',
    storageBucket: 'voleo-sho2303.firebasestorage.app',
    androidClientId:
        '506754202518-uhiakrmn74lp2advmsl3k8tl3hpkeq49.apps.googleusercontent.com',
    iosClientId:
        '506754202518-7r63go6pe02p5t2eko52e8hffckehqdp.apps.googleusercontent.com',
    iosBundleId: 'de.capycode.voleo',
  );
}
